print("Hello, World!")
print()
print("Dipendra\npatel",end=" ")
print("kumar")
print("Dipendra","patel",sep="-")
print("dipendra","patel",sep="***")
print(0o123)
print(0x123)
print(0b10101)
print('I\'m Monty Python.')
print("I'm Monty Python.")
