# for i in range(2,8,2): #here 2 is intial value of i, 8 is max range(excluding 8)  & 2 in increment(e.g: 2,4,6 but not 8)
#     print("The values of i is:",i)

for i in range(1, 1): #if the set generated by the range() function is empty, the loop won't execute its body at all.
    print("The value of i is currently", i)


